[package]
name = "tyche-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.12.0", features = ["dynamic_linking"] }
bevy_egui = "0.24.0"
bevy-inspector-egui = "0.22.1"

serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.111"

reqwest = { version = "0.11.22", features = ["blocking", "json"] }
open = "5.0.1"
jsonwebtoken = "9.2.0"
dotenv = "0.15.0"
