[package]
name = "tyche-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.12.0", features = ["dynamic_linking"] }
bevy_egui = "0.24.0"
serde = { version = "1.0.193", features = ["derive"] }
reqwest = { version = "0.11.22", features = ["blocking", "json"] }
firebase-auth = "0.3.1"
open = "5.0.1"
futures-lite = "2.1.0"
tokio = { version = "1.35.0", features = ["full"] }
