---
# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployement
  labels:
    app: auth
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: europe-west1-docker.pkg.dev/tyche-vtt/tyche/auth:0.1.0
        ports:
          - containerPort: 3000
---
# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  type: NodePort
  selector:
    app: auth
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30000
---

#apiVersion: autoscaling/v2
#kind: HorizontalPodAutoscaler
#metadata:
#  name: auth-hpa-5che
#  namespace: default
#  labels:
#    app: auth
#spec:
#  scaleTargetRef:
#    kind: Deployment
#    name: auth
#    apiVersion: apps/v1
#  minReplicas: 1
#  maxReplicas: 5
#  metrics:
#  - type: Resource
#    resource:
#      name: cpu
#      target:
#        type: Utilization
#        averageUtilization: 80
